vich_uploader:
    db_driver: orm

    mappings:
        program:
            uri_prefix: '%upload_path%'
            namer: App\Naming\VichNaming
            upload_destination: '%kernel.project_dir%/public/%upload_path%'
