vich_uploader:
    db_driver: orm

    mappings:
        program:
            uri_prefix: '%upload_path%'
            namer:
                #one of: vich_uploader.namer_{uniqid,origname,property,hash}
                service: vich_uploader.namer_origname
            upload_destination: '%kernel.project_dir%/public/%upload_path%'
