easy_admin:
  entities:
    Filter:
      label: "Filtres"
      class: App\Entity\Filter
      list:
        title: 'Liste des filtres'
        actions:
          - {name: 'new', label: 'Créer un filtre'}
        fields:
          - {property: 'name', label: 'Nom du filtre'}
          - {property: 'filterOption', label: 'Option du filtre'}
          - {property: 'programs', label: 'Programmes associés'}
      new:
        title: "Création d'un filtre"
      edit:
        title: "Modification d'un filtre"
      form:
        fields:
          - {property: 'name', label: 'Nom du filtre'}
          - {property: 'filterOption', label: 'Option du filtre'}