easy_admin:
  entities:
    Homepage:
      label: "Page d'accueil"
      disabled_actions: ['new', 'delete' ]
      class: App\Entity\Homepage
      edit:
        fields:
          - { property: 'text' }
      list:
        sort: ['listorder', 'ASC']
        fields:
          - {property: 'listorder', label: 'Ordre'}
          - {property: 'name', label: 'Nom'}
          - {property: 'text', label: 'Texte' }