easy_admin:
  entities:
    OwnerHome:
      label: "Intro"
      disabled_actions: ['new', 'delete' ]
      class: App\Entity\OwnerHome
      list:
        sort: ['listorder', 'ASC']
        fields:
          - {property: 'listorder', label: 'Ordre'}
          - {property: 'name', label: 'Nom'}
      edit:
        title: "Modification du texte"
        fields:
          - {property: 'description', label: 'Texte', type: 'fos_ckeditor'}