easy_admin:
  entities:
    OwnerArticle:
      label: "Article"
      class: App\Entity\OwnerArticle
      list:
        actions:
          - {name: 'new', label: 'Créer un article'}
        fields:
          - {property: 'title', label: 'Titre'}
          - {property: 'picture', label: 'Image', type: 'image', base_path: '%upload_path_owner%'}
          - {property: 'ownerSubcategory', label: 'Sous catégorie'}
          - {property: 'ownerSubcategory.ownerCategory', label: 'Catégorie'}
      new:
        title: "Création d'article"
      edit:
        title: "Modification d'un article"
      form:
        fields:
          - {property: 'title', label: 'Titre'}
          - {property: 'text', label: 'Texte', type: 'fos_ckeditor'}
          - {property: 'pictureFile', label: 'Image', type: 'vich_image'}
          - {property: 'pictureAlt', label: "Texte alternatif à l'image"}
          - {property: 'owner_subcategory', label: "Sous catégorie associée"}
          - {property: 'published', label: "Publié ?"}
          - {property: 'pagetitle', label: "Titre de la page"}
          - {property: 'metatitle', label: "Balise title"}
          - {property: 'metadescription', label: "Meta description"}