easy_admin:
  entities:
    ProgramCategory:
      label: "Programme (catégorie)"
      class: App\Entity\ProgramCategory
      list:
        actions:
          - {name: 'new', label: 'Créer un programme'}
        fields:
          - {property: 'name', label: 'Nom'}
          - {property: 'program', label: 'Programmes associés'}
      new:
        title: "Création d'un programme"
      edit:
        title: "Modification d'un programme"
      form:
        fields:
          - {property: 'name', label: 'Nom'}