easy_admin:
  entities:
    Program:
      label: "Programmes"
      class: App\Entity\Program
      list:
        title: 'Liste des programmes'
        actions:
          - { name: 'new', label: 'Ajouter un bien'}
          - { name: 'managePictures', label: 'Gérer les images'}
          - { name: 'manageProperty', label: 'Gérer les biens'}
        fields:
          - {property: 'name', label: 'Nom du bien'}
          - {property: 'city', label: 'Ville'}
          - {property: 'published', label: 'Publié ?'}
          - {property: 'filter', type: 'array', label: 'Filtres'}
      new:
        title: "Création d'un bien"
      edit:
        title: "Modification d'un bien"
      show:
        title: "Aperçu du bien"
        fields:
          - {property: 'name', label: 'Nom du bien'}
          - {property: 'description', label: 'Description'}
#          - {property: 'descriptionMore', label: 'Description +'}
          - {property: 'address', label: 'Adresse'}
          - {property: 'city', label: 'Ville'}
          - {property: 'postcode', label: 'Code postal'}
          - {property: 'region', label: 'Région'}
          - {property: 'price', label: 'Prix'}
          - {property: 'typologie', label: 'Typologie'}
          - {property: 'numberRooms', label: 'Nombre de pièces'}
          - {property: 'surface', label: 'Surface'}
          - {property: 'movie', label: 'Vidéo'}
          - {property: 'dateDelivery', label: 'Date de livraison'}
          - {property: 'main_criteria', label: 'Points forts'}
          - {property: 'criteria', label: 'Critères'}
          - {property: 'program_picture', label: 'Images associées'}
          - {property: 'filter', label: "Filtres pour la page d'accueil"}
          - {property: 'published', label: 'Publié ?'}
          - {property: 'url', label: 'URL absolue vers blog' }
          - {property: 'published', label: 'Publié ?' }
          - {property: 'pagetitle', label: 'Titre de la page' }
          - {property: 'metatitle', label: 'Meta title' }
          - {property: 'metadescription', label: 'Meta description' }
          - {property: 'slug', label: 'Slug' }
      form:
        fields:
          - {property: 'name', label: 'Nom du bien'}
#          - {property: 'descriptionMore', label: 'Description +'}
          - {property: 'description', type: 'fos_ckeditor', label: 'Description principale' }
          - {property: 'address', label: 'Adresse' }
          - {property: 'city', label: 'Ville', type_options: { required: true } }
          - {property: 'postcode', type: 'integer', label: 'Code postal' }
          - {property: 'region', label: 'Région' }
          - {property: 'price', label: 'prix' }
          - {property: 'typologie', label: 'Typologie' }
          - {property: 'numberRooms', label: 'Nombre de pièces', type: 'number' }
          - {property: 'surface', label: 'Surface' }
          - {property: 'planFile', label: "Plan du programme", type: 'vich_image' }
          - {property: 'movie', label: "Iframe d'une vidéo" }
          - {property: 'dateDelivery', label: 'Date de livraison', type: 'date', type_options:{'widget':'single_text'} }
          - {property: 'main_criteria', label: 'Points forts' }
          - {property: 'criteria', label: 'Critères' }
          - {property: 'filter', label: 'Filtres' }
          - {property: 'url', label: 'URL absolue vers blog' }
          - {property: 'published', label: 'Publié ?' }
          - {property: 'pagetitle', label: 'Titre de la page' }
          - {property: 'metatitle', label: 'Balise Title' }
          - {property: 'metadescription', label: 'Meta description' }
          - {property: 'slug', label: 'Slug', type_options: { required: true } }
