easy_admin:
  entities:
    SearchPage:
      label: "Page 'Trouvez un logement'"
      disabled_actions: ['new', 'delete' ]
      class: App\Entity\SearchPage
      edit:
        title: "Modification du texte"
        fields:
          - { property: 'text', type: 'fos_ckeditor', label: "Texte" }
      list:
        fields:
          - {property: 'name', label: 'Nom'}