easy_admin:
  entities:
    SearchBrochure:
      label: "Brochures"
      disabled_actions: ['new', 'delete' ]
      class: App\Entity\SearchBrochure
      edit:
        title: 'Modifier la brochure'
        fields:
          - { property: 'fileFile', type: 'vich_image', label: 'Brochure' }
      list:
        fields:
          - {property: 'name', label: 'Nom'}