easy_admin:
  entities:
    SearchPage:
      label: "Page 'Trouvez un logement'"
      disabled_actions: ['new', 'delete' ]
      class: App\Entity\SearchPage
      edit:
        title: "Modification du texte"
        fields:
          - { property: 'text', label: "Texte", type: 'fos_ckeditor' }
      list:
        sort: ['listorder', 'ASC']
        fields:
          - {property: 'listorder', label: 'Ordre'}
          - {property: 'name', label: 'Nom'}