easy_admin:
  entities:
    User:
      label: "Utilisateurs"
      class: App\Entity\User
      list:
        fields:
          - {property: 'username', label: "Nom d'utilisateur"}
          - {property: 'email', label: "Email"}
          - {property: 'enabled', label: "Activé ?"}
      new:
        title: "Création d'un nouvel administrateur"
        fields:
          - {property: 'username', label: "Nom d'utilisateur"}
          - {property: 'email', label: "Email"}
          - {property: 'enabled', label: "Activé ?"}
          - { property: 'plainPassword', label: "Mot de passe", type: 'text', type_options: { required: true } }
      edit:
        title: "Modification de l'administrateur"
        fields:
          - {property: 'username', label: "Nom d'utilisateur"}
          - {property: 'email', label: "Email"}
          - {property: 'enabled', label: "Activé ?"}
          - { property: 'plainPassword', label: "Mot de passe", type: 'password', type_options: { required: false } }
